# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8654a045eb0ba44ae2de29bb91d0120c0375f4accf52ed5ea7ac8fe4fea1f0a4b53caa2ca4a9ce406d97ac3e113f2feac10354ca22c75e4ffef47e0293715094

test:
  secret_key_base: 1892af2d370faa240931bcdff73954ab495e4d0d706cd0f62b742ede0bf28f8074119436d37cd569603d6eb879fdc283c51cb165d9b5e5f30f84e0d22b413034

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
